### PR TITLE
 #101 Fix node flattening system

### LINKED ISSUE #101: Last graph node has empty details
**Describe the bug**
The last node of every graph contains an empty details object.

**To Reproduce**
1. Go to some fragment's details
2. Click on the last executed node
3. A tab with node's details opens

**Expected behavior**
The tab contains debug data of the node.

### PR DESCRIPTION
**Pull request by Voycawojka**
Fixes #101.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the [code style](/CONTRIBUTING.md#coding-conventions) of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

---
I hereby agree to the terms of the Knot.x Contributor License Agreement.

### CODE REVIEW

File: src/js/helpers/graph/declarationHelper.js [hunk 1]
```diff
@@ -86,7 +86,10 @@ const createVirtualEndNode = (composite, transitions) => ({
 });
 
 const createTransitionsToSubtasks = (subtasks) => subtasks
```
Comment (MichalGraziowskiCognifide) [inline src/js/helpers/graph/declarationHelper.js:88]: Out of curiosity: Why do you make subtasks an object instead of array?

File: src/js/helpers/graph/declarationHelper.js [hunk 2]
```diff
@@ -86,7 +86,10 @@ const createVirtualEndNode = (composite, transitions) => ({
...
-  .reduce((total, current, index) => ({ ...total, [`_subtask_${index}`]: current }), {});
+  .reduce((total, current, index) => ({
```
Comment (MichalGraziowskiCognifide) [inline src/js/helpers/graph/declarationHelper.js:89]: btw. for large number of subtasks this is going to be extremely slow.
This is more efficient `Object.fromEntries(subtasks.map((task,index) => [`_subtask_${index}`, task]))` 

https://www.richsnapp.com/article/2019/06-09-reduce-spread-anti-pattern

Comment (MichalGraziowskiCognifide) [reply src/js/helpers/graph/declarationHelper.js:89]: I let myself create a small benchmark:
image
image

File: src/js/helpers/graph/declarationHelper.js (hunk 1 above)
Comment (Voycawojka) [reply src/js/helpers/graph/declarationHelper.js:88]: Because this whole function creates a graph that do not distinct between subtasks and normal nodes so if they would be an array I would have to have a check for that in a few different places in the code

File: src/js/helpers/graph/declarationHelper.js (hunk 2 above)
Comment (Voycawojka) [reply src/js/helpers/graph/declarationHelper.js]: Nice, didn't know about `fromEntries` function

File: src/js/helpers/graph/declarationHelper.js [hunk 3]
```diff
@@ -85,8 +85,14 @@ const createVirtualEndNode = (composite, transitions) => ({
   },
 });
 
-const createTransitionsToSubtasks = (subtasks) => subtasks
-  .reduce((total, current, index) => ({ ...total, [`_subtask_${index}`]: current }), {});
+// const createTransitionsToSubtasks = (subtasks) => subtasks
+//   .reduce((total, current, index) => ({
+//     ...total,
+//     [`_subtask_${index}`]: current,
+//   }), {});
```
Comment (MichalGraziowskiCognifide) [inline src/js/helpers/graph/declarationHelper.js:92]: It's not needed then ;)
